"""Add is_active to users

Revision ID: 8228a4fa8dd9
Revises: 
Create Date: 2025-12-18 22:24:13.216909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8228a4fa8dd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificates_cert_id'))
        batch_op.drop_index(batch_op.f('ix_certificates_file_id'))
        batch_op.drop_index(batch_op.f('ix_certificates_user_id'))
        batch_op.create_unique_constraint(None, ['cert_id'])

    with op.batch_alter_table('file_shares', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_filehash'))
        batch_op.drop_index(batch_op.f('ix_files_user_id'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_filehash'), ['filehash'], unique=False)

    with op.batch_alter_table('file_shares', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_certificates_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_cert_id'), ['cert_id'], unique=1)

    # ### end Alembic commands ###
